"""optimize_schema_indexes

Revision ID: bdcc9f8d8d4b
Revises: 
Create Date: 2026-07-04 21:21:20.573300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdcc9f8d8d4b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_campaign_members_delivery_status'), 'campaign_members', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_campaign_members_read_status'), 'campaign_members', ['read_status'], unique=False)
    op.create_index(op.f('ix_campaign_members_wa_message_id'), 'campaign_members', ['wa_message_id'], unique=False)
    op.drop_constraint(op.f('campaign_members_member_id_fkey'), 'campaign_members', type_='foreignkey')
    op.drop_constraint(op.f('campaign_members_campaign_id_fkey'), 'campaign_members', type_='foreignkey')
    op.create_foreign_key(None, 'campaign_members', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'campaign_members', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_campaigns_status'), 'campaigns', ['status'], unique=False)
    op.create_index(op.f('ix_chat_messages_direction'), 'chat_messages', ['direction'], unique=False)
    op.create_index(op.f('ix_chat_messages_message_type'), 'chat_messages', ['message_type'], unique=False)
    op.create_index(op.f('ix_chat_messages_status'), 'chat_messages', ['status'], unique=False)
    op.drop_constraint(op.f('chat_messages_member_id_fkey'), 'chat_messages', type_='foreignkey')
    op.create_foreign_key(None, 'chat_messages', 'members', ['member_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_members_membership_type'), 'members', ['membership_type'], unique=False)
    op.create_index(op.f('ix_members_status'), 'members', ['status'], unique=False)
    op.alter_column('templates', 'body_text',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_templates_category'), 'templates', ['category'], unique=False)
    op.create_index(op.f('ix_templates_status'), 'templates', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_status'), table_name='templates')
    op.drop_index(op.f('ix_templates_category'), table_name='templates')
    op.alter_column('templates', 'body_text',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_members_status'), table_name='members')
    op.drop_index(op.f('ix_members_membership_type'), table_name='members')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.create_foreign_key(op.f('chat_messages_member_id_fkey'), 'chat_messages', 'members', ['member_id'], ['id'])
    op.drop_index(op.f('ix_chat_messages_status'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_message_type'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_direction'), table_name='chat_messages')
    op.drop_index(op.f('ix_campaigns_status'), table_name='campaigns')
    op.drop_constraint(None, 'campaign_members', type_='foreignkey')
    op.drop_constraint(None, 'campaign_members', type_='foreignkey')
    op.create_foreign_key(op.f('campaign_members_campaign_id_fkey'), 'campaign_members', 'campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(op.f('campaign_members_member_id_fkey'), 'campaign_members', 'members', ['member_id'], ['id'])
    op.drop_index(op.f('ix_campaign_members_wa_message_id'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_read_status'), table_name='campaign_members')
    op.drop_index(op.f('ix_campaign_members_delivery_status'), table_name='campaign_members')
    # ### end Alembic commands ###
